FROM antoineb/kalilinux-arm

ENV DEBIAN_FRONTEND noninteractive
ADD sources.list /etc/apt/
RUN 	apt-get update
RUN     apt-get -o Dpkg::Options::="--force-confdef" dist-upgrade -y
RUN     apt-get install -y kali-defaults kali-root-login x11vnc autocutsel xvfb supervisor kali-linux-web
RUN /etc/init.d/dbus start
#RUN     apt-get install -y bluez
#RUN     usermod -G bluetooth -a root
#RUN     apt-get install -y --reinstall blueman
RUN     apt-get install -y desktop-base mate-core mate-desktop-environment-extra mate-desktop-environment-extras
	
RUN mkdir -p /root/.x11vnc /root/.vnc/certs/ /data &&\
	ln -s /data /root/Documents &&\
	x11vnc -storepasswd passw0rd /root/.x11vnc/passwd

ADD agent.conf /etc/supervisor/conf.d
ADD supervisord.conf /etc/supervisor
ADD server.pem /root/.vnc/certs/

ENV DISPLAY ":0.0"

EXPOSE 5901

WORKDIR /data

CMD /usr/bin/supervisord --nodaemon --configuration /etc/supervisord.conf
